import Head from 'next/head'
import Image from 'next/image'
import Banner from '../components/Banner'
import Header from '../components/Header'
import ProductFeed from '../components/ProductFeed'
import { Product } from '../typing'

interface props {
 products: Product[],
}

export default function Home({products}:props) {
  
  return (
    <div className='bg-gray-100'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <main className='max-w-screen-2xl mx-auto'>
        {/* banner */}
        <Banner/>
        {/* product feed */}
        <ProductFeed products={products}/>
      </main>
    </div>
  )
}


export async function getServerSideProps()  {
  const products = await fetch('https://fakestoreapi.com/products')
  .then(res=>res.json());
  return {
    props: {
      products
    }
  }
}